Update message-handlers.ts
yonilerner/yonebot pull request #6
Opened 2022-11-27 07:09 UTC by zzackey

added uni

2022-11-27 17:23 UTC, promise requested changes
still wouldn't work

2022-11-27 17:28 UTC, zzackey commented
I think I did it. Probably!

2022-11-29 00:10 UTC, yonilerner commented on src/message-handlers.ts
> +  if ((message.content.toLowerCase().includes('yoni')) ||  (message.content.toLowerCase().includes('uni')) ||  (message.content.toLowerCase().includes('yone')) {
- you dont need the extra parens
- youre calling `message.content.toLowerCase()` 3 times - could be saved in a variable
- this is too sensitive to things like `@everyone` - word break regexes should be used probably. once using regex, u dont need to lowercase it
- what if we want to add more words? I'd suggest an array of words you want to check for, and then check if any of them are in the list:

```ts
// outside of `handleMessage` function
const wordsToReactTo = [/\byoni/i, /\buni/i, /\byone/i]
...
// inside of `handleMessage` function
if (wordsToReactTo.some(regex => regex.test(message.content)) {
...
}
```

2022-12-04 19:58 UTC, appellation approved these changes

2022-12-04 19:58 UTC, appellation commented on src/message-handlers.ts
> +
This is critical. Huge QoL improvement.

2022-12-04 20:28 UTC, merged